// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package BlogDB

import (
	"database/sql"
	"time"
)

type Blog struct {
	BlogID    int64
	Title     string
	Content   string
	UserID    int64
	FirstName string
	LastName  string
	FullName  string
	Email     string
}

type User struct {
	UserID        int64
	FullName      string
	FirstName     string
	LastName      string
	Email         string
	Role          sql.NullString
	DateOfBirth   sql.NullTime
	UserAddress   sql.NullString
	BlogsUploaded sql.NullInt32
	Status        sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type UserCredential struct {
	ID        int64
	Uid       int64
	Email     string
	Password  string
	FirstName string
	LastName  string
	Role      string
}

type UserSession struct {
	SessionID int64
	Uid       int64
	Email     string
	Token     string
	UserAgent string
	Role      string
	CreatedAt time.Time
	Status    bool
}
